# docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - dependabot
      - javascript
      - verified
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
    target-branch: "releases/v3.0"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependabot
      - github-actions
      - verified
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
    target-branch: "releases/v3.0"